remote_theme: ShipEngine/gh-pages-theme

title: ShipEngine IPaaS
logo: https://jstools.dev/img/logos/logo.png

author:
  twitter: ShipEngineAPI

google_analytics: UA-68102273-3

twitter:
  username: ShipEngineAPI
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://jstools.dev/img/logos/card.png
  - scope:
      path: "test/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
