/**
 * A well-known service that's often used to fulfill a carrier's delivery services.
 */
export enum FulfillmentService {
  DHLEconomySelect = "dhl_economy_select",
  DHLExpressDomestic = "dhl_express_domestic",
  DHLExpressDomestic9am = "dhl_express_domestic_9am",
  DHLExpressDomestic12pm = "dhl_express_domestic_12pm",
  DHLExpressEnvelope = "dhl_express_envelope",
  DHLExpressWorldwide = "dhl_express_worldwide",
  DHLExpressWorldwide9am = "dhl_express_worldwide_9am",
  DHLExpressWorldwide1030am = "dhl_express_worldwide_1030am",
  DHLExpressWorldwide12pm = "dhl_express_worldwide_12pm",
  DHLExpressEconomySelect = "dhl_express_economy_select",

  FedExEconomy = "fedex_economy",
  FedExExpressSaver = "fedex_express_saver",
  FedExGround = "fedex_ground",
  FedExGroundInternational = "fedex_ground_international",
  FedExHomeDelivery = "fedex_home_delivery",
  FedEx2Day = "fedex_2day",
  FedEx2DayAM = "fedex_2_day_am",
  FedExNextDay = "fedex_next_day",
  FedExNextDay10am = "fedex_next_day_10am",
  FedExNextDay12pm = "fedex_next_day_12pm",
  FedExSmartPostPresortedStandard = "fedex_smartpost_presorted_standard",
  FedExSmartPostParcelSelect = "fedex_smartpost_parcel_select",
  FedExSmartPostParcelSelectLightweight = "fedex_smartpost_parcel_select_lightweight",
  FedExInternationalPriority = "fedex_international_priority",
  FedExPriorityOvernight = "fedex_priority_overnight",
  FedExInternationalEconomy = "fedex_international_economy",
  FedExFirstOvernight = "fedex_first_overnight",
  FedExInternationalFirst = "fedex_international_first",
  FedExStandardOvernight = "fedex_standard_overnight",
  FedExSmartPostMedia = "fedex_smartpost_media",
  FedExInternationalMailService = "fedex_international_mailservice",

  UPSGround = "ups_ground",
  UPSGroundInternational = "ups_ground_international",
  UPSExpress = "ups_express",
  UPSExpressPlus = "ups_express_plus",
  UPSExpressEarly = "ups_express_early",
  UPSWorldwideExpress = "ups_worldwide_express",
  UPSWorldwideExpedited = "ups_worldwide_expedited",
  UPSWorldwideExpressPlus = "ups_worldwide_express_plus",
  UPSWorldwideSaver = "ups_worldwide_saver",
  UPSNextDayAir = "ups_next_day_air",
  UPSNextDayAirInternational = "ups_next_day_air_international",
  UPSNextDayAirSaver = "ups_next_day_air_saver",
  UPS2DayAir = "ups_2_day_air",
  UPS2DayAirAM = "ups_2_day_air_am",
  UPS2DayAirInternational = "ups_2_day_air_international",
  UPS3DaySelect = "ups_3_day_select",
  UPSNextDayAirEarly = "ups_next_day_air_early",
  UPSStandard = "ups_standard",
  UPSSurePostMedia = "ups_surepost_media",
  UPSMailInnovationsFirstClass = "ups_mail_innovations_first_class",
  UPSMailInnovationsExpedited = "ups_mail_innovations_expedited",
  UPSMailInnovationsPriority = "ups_mail_innovations_priority",
  UPSMailInnovationsEconomy = "ups_mail_innovations_economy",
  UPSMailInnovationsParcelSelect = "ups_mail_innovations_parcel_select",
  UPSMailInnovationsParcelSelectLightweight = "ups_mail_innovations_parcel_select_lightweight",

  USPSFirstClassMail = "usps_first_class_mail",
  USPSPriorityMail = "usps_priority_mail",
  USPSPriorityMailExpress = "usps_priority_mail_express",
  USPSMediaMail = "usps_media_mail",
  USPSParcelSelectGround = "usps_parcel_select_ground",
  USPSFirstClassMailInternational = "usps_first_class_mail_international",
  USPSPriorityMailInternational = "usps_priority_mail_international",
  USPSPriorityMailExpressInternational = "usps_priority_mail_express_international",
}
