name: Custom Store Build and Test and Publish

on: 
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM Login
      run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Publish NPM Module
      run: npm publish